### ISSUE TITLE
hardhat-zksync-chai-matchers: revertedWith reason is not what it should be when running on local-setup

### ISSUE THREAD

**Issue by antonklyr** [matter-labs/hardhat-zksync#254] opened 2023-04-12 22:28 UTC
Hello,

I am running tests with hardhat-zksync-chai-matchers' revertedWith property, which seems to be parsing a wrong reason from the error data.

I am testing a simple onlyOwner function, and I should get the `Ownable: caller is not the owner`, but instead I get ` caller is not the owne`

Full error message: `AssertionError: Expected transaction to be reverted with reason 'Ownable: caller is not the owner', but it reverted with reason ' caller is not the owne'`

I believe the reason to be in the [utils.ts](https://github.com/matter-labs/hardhat-zksync/blob/main/packages/hardhat-zksync-chai-matchers/src/internal/reverted/utils.ts) file, where the "message" is expected to start with `Cannot estimate transaction: ` and end with a dot. However, with the local-setup, I receive a message starting with `cannot estimate gas: ` and not ending with a dot, resulting in the odd truncation.

Full error data: `{\"code\":104,\"message\":\"cannot estimate gas: Ownable: caller is not the owner\"}}`

Thank you in advance for your help!

**Comment by mpopovac-txfusion** [comment] 2023-04-27 08:28
Thanks for the feedback. There is indeed an error in the chai matchers caused by changes in the local-setup (localnode image updated). We are currently working on the changes related to localnode and as soon as we finish them, a new version of the plugin will be released.

**Closed** 2023-05-13 10:55 UTC
